services:
  - type: web
    name: smart-menu
    env: node
    buildCommand: npm install && npx prisma generate && npx next build
    startCommand: npx next start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
